/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#353436',
        'on-surface': '#e5e2e3',
        'tertiary-container': '#0072d7',
        'inverse-surface': '#e5e2e3',
        'on-background': '#e5e2e3',
        'surface-container': '#201f20',
        'surface-container-high': '#2a2a2b',
        'on-secondary-fixed': '#2c0051',
        'primary-fixed': '#ffdad5',
        outline: '#af8782',
        'on-tertiary-container': '#f8f9ff',
        'on-tertiary': '#003061',
        tertiary: '#a7c8ff',
        'on-primary-container': '#fff7f6',
        'inverse-primary': '#c0000c',
        'on-primary-fixed': '#410001',
        'surface-container-lowest': '#0e0e0f',
        'tertiary-fixed': '#d5e3ff',
        error: '#ffb4ab',
        background: '#131314',
        'on-tertiary-fixed-variant': '#004689',
        'on-tertiary-fixed': '#001b3c',
        'primary-fixed-dim': '#ffb4aa',
        'surface-bright': '#3a393a',
        'on-surface-variant': '#e9bcb6',
        'outline-variant': '#5e3f3b',
        'surface-dim': '#131314',
        'on-secondary': '#480081',
        'surface-tint': '#ffb4aa',
        'on-secondary-container': '#dcb7ff',
        'secondary-container': '#7701d0',
        'on-primary': '#690003',
        'surface-container-highest': '#353436',
        'on-primary-fixed-variant': '#930007',
        surface: '#131314',
        'error-container': '#93000a',
        'inverse-on-surface': '#313031',
        'primary-container': '#e50914',
        'secondary-fixed-dim': '#dcb8ff',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#6700b5',
        'surface-container-low': '#1c1b1c',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#a7c8ff',
        secondary: '#dcb8ff',
        'secondary-fixed': '#efdbff',
        primary: '#ffb4aa',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Lexend', 'sans-serif'],
        'headline-lg': ['Lexend', 'sans-serif'],
        'display-lg': ['Lexend', 'sans-serif'],
        'display-lg-mobile': ['Lexend', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        float: 'float 6s ease-in-out infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
}
